### ISSUE TITLE
Unable to send events to Compass

### ISSUE THREAD

**Issue by yavir-me** [atlassian-labs/Compass-Orb#14]
Here's my `.circleci/config.yml` file configurations:
```
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.18
  compass: atlassian-labs/compass@0.1.2

executors:
  compass-executor:
    docker:
      - image: circleci/node:14

  make_compass_notification:
    executor: compass-executor
    steps:
      - compass/notify_deployment

workflows:
  version: 2
  production:
    jobs:
       - make_compass_notification:
                context: compass-integration-zsu-electronics
                requires:
                  - make_cloudfront_invalidation
...

``` 

```
{
  "workflowId": "5c1370dc-f07b-42ae-94f5-a86c30d85f40",
  "jobId": "228",
  "lastUpdated": "2023-06-29T07:31:05+00:00",
  "status": "SUCCESSFUL",
  "deployments": [
    {
      "environment": {
        "category": "DEVELOPMENT",
        "displayName": "development",
        "environmentId": "development"
      },
      "lastUpdated": "2023-06-29T07:31:05+00:00"
    }
  ]
}
Results from Compass: 
Error calling Compass, result: 400
{
  "errorMessage": "Unable to send events to Compass",
  "success": false
}
```
